version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend:/app/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: nginx:1.19.3
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media/
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
