version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend:/app/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: ./infra/
    restart: always
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
