version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    env_file:  ../.env
    volumes:
      - db-data:/var/lib/postgresql/data/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    env_file: ../.env
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - ../backend:/app/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  db-data:
