# Generated by Django 3.2.16 on 2023-11-25 04:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Enter a unique username.', max_length=150, unique=True, validators=[core.validators.validate_username, core.validators.RegexUsername], verbose_name='Username'),
        ),
    ]
