# Generated by Django 3.2.16 on 2023-11-25 04:36

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231125_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Enter a unique username.', max_length=150, unique=True, validators=[core.validators.validate_username, django.core.validators.RegexValidator(message='The username contains invalid characters.', regex='^[\\w.@+-]+$')], verbose_name='Username'),
        ),
    ]
